[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bountify = "GV82BHGtQ3UaantPYTWkD3i4rVuerkHyDwq6rMKXURMC"

[registry]
url = "https://api.devenet.solana.com"

[provider]
cluster = "devnet"
wallet = "/home/linux/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
